#!/bin/bash

set -e

# image name and tag
GO_DEV_SH_IMAGE_TAG="${GO_DEV_SH_IMAGE_TAG:-otaviof/go-dev-sh:latest}"
# base directory, where all data will be placed upon
BASE_DIR="${HOME}/.go-dev-sh"
# custom GOPATH directory
GOPATH_DIR="${BASE_DIR}/gopath"
# bash directory, to save histfile
BASH_DIR="${BASE_DIR}/bash.d"

# current directory name, to be mounted on container
CUR_DIR_NAME="$(basename ${PWD})"

# creating directories to be mounted on container
[ -d "${GOPATH_DIR}" ] || mkdir -p "${GOPATH_DIR}"
[ -d "${BASH_DIR}" ] || mkdir -p "${BASH_DIR}"

echo "# Go development container for: ${CUR_DIR_NAME} at /src/${CUR_DIR_NAME}"

exec docker run \
    --interactive \
    --tty \
    --volume "${GOPATH_DIR}:/go" \
    --volume "${BASH_DIR}:/root/.bash.d" \
    --volume "${PWD}:/src/${CUR_DIR_NAME}" \
    --workdir "/src/${CUR_DIR_NAME}" \
    ${GO_DEV_SH_IMAGE_TAG}
